---

- name: Copy files to remote
  hosts: web

  tasks:
    - name: Copy files
      copy: 
        src: /Users/Sahil/Desktop/Ansible-Playbooks
        dest: /home/ubuntu
        owner: Paul
        group: DevOps
        mode: 0777
